name: test:city-distance-application
on:
  workflow_dispatch:
jobs:
  gitHubActionForPytest:
    name: City Distance Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test City Distance Application
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: python setup.py develop && pytest __tests__/test_cities-distance.py -vs
